use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use crate::core::write_atomic;

fn home() -> Option<PathBuf> {
    env::var_os("HOME").map(PathBuf::from)
}

fn config_dir_from(xdg: Option<&Path>, home: Option<&Path>) -> Option<PathBuf> {
    xdg.map(Path::to_path_buf)
        .or_else(|| home.map(|home| home.join(".config")))
}

fn config_dir() -> std::io::Result<Option<PathBuf>> {
    let xdg = env::var_os("XDG_CONFIG_HOME").map(PathBuf::from);
    let home = home();
    for (name, path) in [("XDG_CONFIG_HOME", xdg.as_ref()), ("HOME", home.as_ref())] {
        if let Some(path) = path {
            if path.as_os_str().is_empty() || !path.is_absolute() {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    format!("{name} must be a non-empty absolute path"),
                ));
            }
        }
    }
    Ok(config_dir_from(xdg.as_deref(), home.as_deref()))
}

pub(crate) fn render_fixed(root: &Path, c: &[String; 16], dark: bool) -> std::io::Result<()> {
    let Some(config) = config_dir()? else {
        eprintln!("warning: HOME and XDG_CONFIG_HOME are unset; skipping optional renderers");
        return Ok(());
    };
    let home = home();
    let mut files = Vec::new();
    let gtk = gtk_colors(c);
    optional(&config, "gtk-3.0", "gtk-3.0/gtk.css", &gtk, &mut files)?;
    optional(&config, "gtk-4.0", "gtk-4.0/gtk.css", &gtk, &mut files)?;
    let qt_colors = qt_colors(c);
    for qtver in ["qt5ct", "qt6ct"] {
        optional_qt(&config, qtver, &qt_colors, &mut files)?;
    }
    optional(&config, "kitty", "kitty/retheme-base16.conf", &format!("# generated by retheme\nforeground {}\nbackground {}\nselection_foreground {}\nselection_background {}\n", c[5], c[0], c[7], c[2]), &mut files)?;
    optional(&config, "btop", "btop/themes/retheme-base16.theme", &format!("# generated by retheme\nmain_bg = \"{}\"\nmain_fg = \"{}\"\nhi_fg = \"{}\"\nselected_bg = \"{}\"\nselected_fg = \"{}\"\n", c[0], c[5], c[13], c[2], c[5]), &mut files)?;
    optional(
        &config,
        "nvim",
        "nvim/colors/retheme-base16.lua",
        &nvim_colors(c, dark),
        &mut files,
    )?;
    optional(
        &config,
        "foot",
        "foot/retheme.ini",
        &foot_colors(c),
        &mut files,
    )?;
    optional(
        &config,
        "alacritty",
        "alacritty/retheme.toml",
        &alacritty_colors(c),
        &mut files,
    )?;
    let chromium = config.join("chromium");
    if path_is_symlinked(&chromium)? {
        eprintln!("warning: Chromium config path is symlinked; skipping renderer");
    } else {
        let chromium_exists = match fs::symlink_metadata(&chromium) {
            Ok(metadata) if !metadata.is_dir() => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidInput,
                    "Chromium config path is not a regular directory",
                ));
            }
            Ok(_) => true,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => false,
            Err(error) => return Err(error),
        };
        if chromium_exists {
            let theme_dir = chromium.join("retheme-theme");
            if path_is_symlinked(&theme_dir)? {
                eprintln!("warning: Chromium theme path is symlinked; skipping renderer");
            } else {
                match fs::symlink_metadata(&theme_dir) {
                    Ok(metadata) if !metadata.is_dir() => {
                        return Err(std::io::Error::new(
                            std::io::ErrorKind::InvalidInput,
                            "Chromium generated theme must be a regular directory",
                        ));
                    }
                    Ok(_) => {
                        let mut symlinked_entry = false;
                        let mut unexpected = false;
                        for entry in fs::read_dir(&theme_dir)? {
                            let entry = entry?;
                            let file_type = entry.file_type()?;
                            if file_type.is_symlink() {
                                symlinked_entry = true;
                            } else {
                                unexpected |=
                                    entry.file_name() != "manifest.json" || !file_type.is_file();
                            }
                        }
                        if unexpected {
                            return Err(std::io::Error::new(
                                std::io::ErrorKind::InvalidInput,
                                "Chromium generated theme contains an unexpected entry",
                            ));
                        }
                        if symlinked_entry {
                            eprintln!("warning: Chromium generated theme contains a symlink; skipping renderer");
                        } else {
                            files.push((theme_dir.join("manifest.json"), chromium_manifest(c)));
                        }
                    }
                    Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                        files.push((theme_dir.join("manifest.json"), chromium_manifest(c)));
                    }
                    Err(error) => return Err(error),
                }
            }
        } else {
            eprintln!("warning: Chromium config directory unavailable; skipping renderer");
        }
    }
    let firefox = config.join("mozilla/firefox");
    browser_prefs(&firefox, dark, &mut files)?;
    browser_prefs(&config.join("librewolf"), dark, &mut files)?;
    if let Some(home) = &home {
        let home_firefox = home.join(".mozilla/firefox");
        if home_firefox != firefox {
            browser_prefs(&home_firefox, dark, &mut files)?;
        }
        browser_prefs(&home.join(".librewolf"), dark, &mut files)?;
    }

    let mut safe_files = Vec::with_capacity(files.len());
    for (destination, content) in files {
        if path_is_symlinked(&destination)? {
            eprintln!(
                "warning: renderer destination is symlinked; skipping {}",
                destination.display()
            );
        } else {
            ensure_safe_destination(&destination)?;
            safe_files.push((destination, content));
        }
    }
    let files = safe_files;
    let originals = files
        .iter()
        .map(|(destination, _)| {
            let original = match fs::symlink_metadata(destination) {
                Ok(metadata) if metadata.is_file() => Some(fs::read_to_string(destination)?),
                Ok(_) => {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidInput,
                        format!(
                            "renderer destination is not a regular file: {}",
                            destination.display()
                        ),
                    ))
                }
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
                Err(error) => return Err(error),
            };
            Ok((destination.clone(), original))
        })
        .collect::<std::io::Result<Vec<_>>>()?;
    let stage = root
        .join("cache")
        .join(format!("retheme-render-{}", std::process::id()));
    if fs::symlink_metadata(&stage).is_ok() {
        crate::core::remove_path(&stage)?;
    }
    fs::create_dir_all(&stage)?;
    let result: std::io::Result<()> = (|| {
        for (index, (_, content)) in files.iter().enumerate() {
            fs::write(stage.join(index.to_string()), content)?;
        }
        for (index, (destination, _)) in files.iter().enumerate() {
            let content = fs::read_to_string(stage.join(index.to_string()))?;
            write_atomic(destination, &content)?;
        }
        Ok(())
    })();
    let cleanup = fs::remove_dir_all(&stage);
    match (result, cleanup) {
        (Err(error), cleanup) => {
            let mut rollback = Vec::new();
            for (destination, original) in &originals {
                let restored = match original {
                    Some(content) => write_atomic(destination, content),
                    None => crate::core::remove_path(destination),
                };
                if let Err(restore) = restored {
                    rollback.push(format!("{}: {restore}", destination.display()));
                }
            }
            let mut message = error.to_string();
            if let Err(cleanup) = cleanup {
                message.push_str(&format!("; renderer staging cleanup failed: {cleanup}"));
            }
            if !rollback.is_empty() {
                message.push_str(&format!(
                    "; renderer rollback failed: {}",
                    rollback.join(", ")
                ));
            }
            Err(std::io::Error::other(message))
        }
        (Ok(()), Ok(())) => Ok(()),
        (Ok(()), Err(error)) => {
            eprintln!("warning: renderer staging cleanup failed: {error}");
            Ok(())
        }
    }
}

fn optional_qt(
    config: &Path,
    qtver: &str,
    colors: &str,
    files: &mut Vec<(PathBuf, String)>,
) -> std::io::Result<bool> {
    let dir = config.join(qtver);
    let selected = optional(
        config,
        qtver,
        &format!("{qtver}/colors/reTheme.colors"),
        colors,
        files,
    )?;
    if selected {
        let colors_path = dir.join("colors/reTheme.colors");
        optional(
            config,
            qtver,
            &format!("{qtver}/{qtver}.conf"),
            &format!("[Appearance]\ncolor_scheme_path={}\ncustom_palette=true\nicon_theme=Adwaita\nstyle=Adwaita\n", colors_path.display()),
            files,
        )?;
    }
    Ok(selected)
}

fn path_is_symlinked(path: &Path) -> std::io::Result<bool> {
    let mut current = PathBuf::new();
    for component in path.components() {
        current.push(component.as_os_str());
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => return Ok(true),
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => break,
            Err(error) => return Err(error),
        }
    }
    Ok(false)
}

fn ensure_safe_destination(path: &Path) -> std::io::Result<()> {
    if path_is_symlinked(path)? {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            format!("renderer path is symlinked: {}", path.display()),
        ));
    }
    Ok(())
}

fn optional(
    base: &Path,
    label: &str,
    relative: &str,
    content: &str,
    files: &mut Vec<(PathBuf, String)>,
) -> std::io::Result<bool> {
    let app = base.join(label);
    if path_is_symlinked(&app)? {
        eprintln!("warning: {label} config path is symlinked; skipping renderer");
        return Ok(false);
    }
    match fs::symlink_metadata(&app) {
        Ok(metadata) if !metadata.is_dir() => {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!("{label} config path is not a regular directory"),
            ));
        }
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            eprintln!("warning: {label} config directory unavailable; skipping renderer");
            return Ok(false);
        }
        Err(error) => return Err(error),
    }
    let destination = base.join(relative);
    let parent = destination
        .parent()
        .expect("renderer destination has a parent");
    if path_is_symlinked(parent)? || path_is_symlinked(&destination)? {
        eprintln!("warning: {label} renderer path is symlinked; skipping renderer");
        return Ok(false);
    }
    match fs::symlink_metadata(parent) {
        Ok(metadata) if !metadata.is_dir() => {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!(
                    "renderer parent is not a regular directory: {}",
                    parent.display()
                ),
            ));
        }
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            eprintln!("warning: {label} config directory unavailable; skipping renderer");
            return Ok(false);
        }
        Err(error) => return Err(error),
    }
    files.push((destination, content.into()));
    Ok(true)
}

fn gtk_colors(c: &[String; 16]) -> String {
    format!("@define-color base00 {};\n@define-color base05 {};\n@define-color base0D {};\nwindow, dialog {{ background-color: @base00; color: @base05; }}\n", c[0], c[5], c[13])
}

fn nvim_colors(c: &[String; 16], dark: bool) -> String {
    format!("local c = {{ bg = '{}', fg = '{}', red = '{}', green = '{}', yellow = '{}', blue = '{}', magenta = '{}', cyan = '{}' }}\nnvim.cmd('hi clear')\nnvim.o.background = '{}'\nfor _, group in ipairs({{'Normal', 'NormalFloat'}}) do vim.api.nvim_set_hl(0, group, {{ fg = c.fg, bg = c.bg }}) end\nvim.api.nvim_set_hl(0, 'Comment', {{ fg = '{}' }})\nvim.api.nvim_set_hl(0, 'String', {{ fg = c.green }})\nvim.api.nvim_set_hl(0, 'Function', {{ fg = c.blue }})\nvim.api.nvim_set_hl(0, 'Keyword', {{ fg = c.magenta }})\n", c[0], c[5], c[8], c[11], c[10], c[13], c[14], c[12], if dark { "dark" } else { "light" }, c[3])
}
fn foot_colors(c: &[String; 16]) -> String {
    format!("# generated by retheme\n[colors]\nforeground={}\nbackground={}\nselection-foreground={}\nselection-background={}\n", &c[5][1..], &c[0][1..], &c[5][1..], &c[2][1..])
}

fn alacritty_colors(c: &[String; 16]) -> String {
    format!("# generated by retheme\n[colors.primary]\nbackground = \"{}\"\nforeground = \"{}\"\n[colors.selection]\nbackground = \"{}\"\nforeground = \"{}\"\n", c[0], c[5], c[2], c[5])
}

fn chromium_manifest(c: &[String; 16]) -> String {
    format!("{{\n  \"manifest_version\": 2,\n  \"version\": \"1.0\",\n  \"name\": \"reTheme generated theme\",\n  \"theme\": {{\n    \"colors\": {{\n      \"frame\": [ {}, {}, {} ],\n      \"toolbar\": [ {}, {}, {} ],\n      \"tab_text\": [ {}, {}, {} ]\n    }}\n  }}\n}}\n", u8::from_str_radix(&c[0][1..3],16).unwrap(), u8::from_str_radix(&c[0][3..5],16).unwrap(), u8::from_str_radix(&c[0][5..7],16).unwrap(), u8::from_str_radix(&c[2][1..3],16).unwrap(), u8::from_str_radix(&c[2][3..5],16).unwrap(), u8::from_str_radix(&c[2][5..7],16).unwrap(), u8::from_str_radix(&c[5][1..3],16).unwrap(), u8::from_str_radix(&c[5][3..5],16).unwrap(), u8::from_str_radix(&c[5][5..7],16).unwrap())
}

fn qt_colors(c: &[String; 16]) -> String {
    let indexes = [
        5, 0, 0, 3, 4, 5, 13, 7, 3, 8, 9, 10, 11, 12, 13, 14, 15, 4, 3, 13, 3,
    ];
    let active = indexes
        .iter()
        .map(|index| format!("#ff{}", &c[*index][1..]))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[ColorScheme]\nactive_colors={active}\ndisabled_colors={active}\ninactive_colors={active}\n")
}

fn browser_prefs(
    root: &Path,
    dark: bool,
    files: &mut Vec<(PathBuf, String)>,
) -> std::io::Result<()> {
    if path_is_symlinked(root)? {
        eprintln!("warning: browser config root is symlinked; skipping renderer");
        return Ok(());
    }
    let profiles = root.join("profiles.ini");
    if path_is_symlinked(&profiles)? {
        eprintln!("warning: browser profiles.ini is symlinked; skipping renderer");
        return Ok(());
    }
    let text = match fs::read_to_string(&profiles) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            eprintln!("warning: browser config directory unavailable; skipping renderer");
            return Ok(());
        }
        Err(error) => return Err(error),
    };
    let canonical_root = root.canonicalize()?;
    let mut browser_files = Vec::new();
    let mut skipped_profile = false;
    for line in text.lines().filter_map(|l| l.strip_prefix("Path=")) {
        let relative = Path::new(line);
        if relative.is_absolute()
            || relative
                .components()
                .any(|c| matches!(c, std::path::Component::ParentDir))
        {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "browser profile path must be relative and contained",
            ));
        }
        let profile = root.join(relative);
        if path_is_symlinked(&profile)? {
            eprintln!("warning: browser profile path is symlinked; skipping profile");
            skipped_profile = true;
            continue;
        }
        let profile = match profile.canonicalize() {
            Ok(profile) => profile,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => continue,
            Err(error) => return Err(error),
        };
        if !profile.starts_with(&canonical_root) || !profile.is_dir() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "browser profile outside config root",
            ));
        }
        let prefs = [
            ("ui.systemUsesDarkTheme", if dark { "1" } else { "0" }),
            ("browser.theme.toolbar-theme", if dark { "0" } else { "2" }),
            ("browser.theme.content-theme", if dark { "0" } else { "2" }),
        ];
        let path = profile.join("user.js");
        if path_is_symlinked(&path)? {
            eprintln!("warning: browser user.js path is symlinked; skipping profile");
            skipped_profile = true;
            continue;
        }
        let old = match fs::read_to_string(&path) {
            Ok(old) => old,
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => String::new(),
            Err(err) => return Err(err),
        };
        let mut out: Vec<String> = old
            .lines()
            .filter(|line| {
                !prefs
                    .iter()
                    .any(|(key, _)| line.starts_with(&format!("user_pref(\"{key}\",")))
            })
            .map(str::to_string)
            .collect();
        for (key, value) in prefs {
            out.push(format!("user_pref(\"{key}\", {value});"));
        }
        browser_files.push((path, out.join("\n") + "\n"));
    }
    if !skipped_profile {
        files.extend(browser_files);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn xdg_config_works_without_home() {
        assert_eq!(
            config_dir_from(Some(Path::new("/tmp/config")), None),
            Some(PathBuf::from("/tmp/config"))
        );
        assert_eq!(config_dir_from(None, None), None);
    }

    #[test]
    fn optional_targets_and_generated_helpers_are_selected() {
        let root = env::temp_dir().join(format!("retheme-renderers-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        for path in ["gtk-3.0", "qt5ct/colors", "kitty", "nvim/colors"] {
            fs::create_dir_all(root.join(path)).unwrap();
        }
        let colors: [String; 16] = std::array::from_fn(|index| format!("#{index:06X}"));
        let mut files = Vec::new();
        let gtk = gtk_colors(&colors);
        optional(&root, "gtk-3.0", "gtk-3.0/gtk.css", &gtk, &mut files).unwrap();
        let qt = qt_colors(&colors);
        optional_qt(&root, "qt5ct", &qt, &mut files).unwrap();
        optional(
            &root,
            "kitty",
            "kitty/retheme-base16.conf",
            "selection_foreground #000007\n",
            &mut files,
        )
        .unwrap();
        let nvim = nvim_colors(&colors, true);
        optional(
            &root,
            "nvim",
            "nvim/colors/retheme-base16.lua",
            &nvim,
            &mut files,
        )
        .unwrap();

        assert_eq!(
            files.iter().map(|(path, _)| path).collect::<Vec<_>>(),
            vec![
                &root.join("gtk-3.0/gtk.css"),
                &root.join("qt5ct/colors/reTheme.colors"),
                &root.join("qt5ct/qt5ct.conf"),
                &root.join("kitty/retheme-base16.conf"),
                &root.join("nvim/colors/retheme-base16.lua"),
            ]
        );
        assert!(files[0].1.contains("@define-color base00 #000000;"));
        assert!(files[1].1.starts_with("[ColorScheme]\nactive_colors=#ff"));
        assert!(files[4].1.contains("nvim.o.background = 'dark'"));
        let kitty = files
            .iter()
            .find(|(path, _)| path.ends_with("kitty/retheme-base16.conf"))
            .unwrap();
        assert!(kitty.1.contains("selection_foreground #000007"));
        assert_eq!(foot_colors(&colors), "# generated by retheme\n[colors]\nforeground=000005\nbackground=000000\nselection-foreground=000005\nselection-background=000002\n");
        assert_eq!(alacritty_colors(&colors), "# generated by retheme\n[colors.primary]\nbackground = \"#000000\"\nforeground = \"#000005\"\n[colors.selection]\nbackground = \"#000002\"\nforeground = \"#000005\"\n");
        assert!(chromium_manifest(&colors).contains("\"manifest_version\": 2"));

        fs::create_dir_all(root.join("qt6ct")).unwrap();
        let mut files = Vec::new();
        optional_qt(&root, "qt6ct", &qt, &mut files).unwrap();
        assert!(files.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn optional_missing_is_skipped_but_wrong_type_is_fatal() {
        let root = env::temp_dir().join(format!("retheme-optional-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        let mut files = Vec::new();
        assert!(!optional(&root, "missing", "missing/file", "content", &mut files).unwrap());
        fs::write(root.join("wrong"), "not a directory").unwrap();
        assert!(optional(&root, "wrong", "wrong/file", "content", &mut files).is_err());
        let _ = fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn optional_symlink_paths_are_skipped() {
        use std::os::unix::fs::symlink;

        let root = env::temp_dir().join(format!("retheme-optional-link-{}", std::process::id()));
        let target = root.join("target");
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(target.join("gtk-3.0")).unwrap();
        symlink(&target, root.join("config")).unwrap();
        let mut files = Vec::new();
        assert!(!optional(
            &root.join("config"),
            "gtk-3.0",
            "gtk-3.0/gtk.css",
            "content",
            &mut files
        )
        .unwrap());

        symlink(&target.join("gtk-3.0"), target.join("destination")).unwrap();
        assert!(!optional(
            &target,
            "gtk-3.0",
            "destination/gtk.css",
            "content",
            &mut files
        )
        .unwrap());
        assert!(files.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn render_fixed_skips_symlinked_chromium_theme_entries() {
        use std::os::unix::fs::symlink;

        let root = env::temp_dir().join(format!("retheme-chromium-link-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let config = root.join("config");
        let theme = config.join("chromium/retheme-theme");
        fs::create_dir_all(&theme).unwrap();
        symlink(root.join("manifest-target"), theme.join("manifest.json")).unwrap();
        fs::write(root.join("manifest-target"), "keep").unwrap();

        let old_xdg = env::var_os("XDG_CONFIG_HOME");
        let old_home = env::var_os("HOME");
        env::set_var("XDG_CONFIG_HOME", &config);
        env::remove_var("HOME");
        let colors: [String; 16] = std::array::from_fn(|index| format!("#{index:06X}"));
        render_fixed(&root, &colors, true).unwrap();
        assert_eq!(
            fs::read_to_string(root.join("manifest-target")).unwrap(),
            "keep"
        );
        assert!(fs::symlink_metadata(theme.join("manifest.json"))
            .unwrap()
            .file_type()
            .is_symlink());

        fs::remove_file(theme.join("manifest.json")).unwrap();
        symlink(
            root.join("unexpected-target"),
            theme.join("unexpected-link"),
        )
        .unwrap();
        render_fixed(&root, &colors, true).unwrap();
        assert!(fs::symlink_metadata(theme.join("unexpected-link"))
            .unwrap()
            .file_type()
            .is_symlink());

        match old_xdg {
            Some(value) => env::set_var("XDG_CONFIG_HOME", value),
            None => env::remove_var("XDG_CONFIG_HOME"),
        }
        match old_home {
            Some(value) => env::set_var("HOME", value),
            None => env::remove_var("HOME"),
        }
        let _ = fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn browser_symlink_paths_are_skipped() {
        use std::os::unix::fs::symlink;

        let root = env::temp_dir().join(format!("retheme-browser-links-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("real/profile")).unwrap();
        fs::write(root.join("real/profiles.ini"), "Path=profile\n").unwrap();

        symlink(root.join("real"), root.join("root-link")).unwrap();
        let mut files = Vec::new();
        browser_prefs(&root.join("root-link"), true, &mut files).unwrap();
        assert!(files.is_empty());

        fs::copy(
            root.join("real/profiles.ini"),
            root.join("profiles.ini.target"),
        )
        .unwrap();
        let mut files = Vec::new();
        browser_prefs(&root.join("real"), true, &mut files).unwrap();
        assert_eq!(files.len(), 1);

        symlink(root.join("real/profile"), root.join("real/profile-link")).unwrap();
        fs::write(
            root.join("real/profiles.ini"),
            "Path=profile\nPath=profile-link\n",
        )
        .unwrap();
        let existing = (root.join("existing"), String::from("keep"));
        let mut files = vec![existing.clone()];
        browser_prefs(&root.join("real"), true, &mut files).unwrap();
        assert_eq!(files, vec![existing]);

        fs::remove_file(root.join("real/profiles.ini")).unwrap();
        symlink(
            root.join("profiles.ini.target"),
            root.join("real/profiles.ini"),
        )
        .unwrap();
        let mut files = Vec::new();
        browser_prefs(&root.join("real"), true, &mut files).unwrap();
        assert!(files.is_empty());

        fs::remove_file(root.join("real/profiles.ini")).unwrap();
        fs::write(root.join("real/profiles.ini"), "Path=profile-link\n").unwrap();
        let mut files = Vec::new();
        browser_prefs(&root.join("real"), true, &mut files).unwrap();
        assert!(files.is_empty());

        fs::remove_file(root.join("real/profiles.ini")).unwrap();
        fs::write(root.join("real/profiles.ini"), "Path=profile\n").unwrap();
        fs::write(root.join("user.js.target"), "user_pref(\"x\", true);\n").unwrap();
        symlink(
            root.join("user.js.target"),
            root.join("real/profile/user.js"),
        )
        .unwrap();
        let mut files = Vec::new();
        browser_prefs(&root.join("real"), true, &mut files).unwrap();
        assert!(files.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[cfg(unix)]
    #[test]
    fn browser_symlinked_profile_still_validates_later_profiles() {
        use std::os::unix::fs::symlink;

        let root = env::temp_dir().join(format!(
            "retheme-browser-link-validation-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("profile")).unwrap();
        symlink(root.join("profile"), root.join("profile-link")).unwrap();
        fs::write(
            root.join("profiles.ini"),
            "Path=profile-link\nPath=../outside\n",
        )
        .unwrap();
        let existing = (root.join("existing"), String::from("keep"));
        let mut files = vec![existing.clone()];

        assert!(browser_prefs(&root, true, &mut files).is_err());
        assert_eq!(files, vec![existing]);
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn browser_preflight_errors_propagate() {
        let root = env::temp_dir().join(format!("retheme-browser-invalid-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        fs::write(root.join("profiles.ini"), "Path=../outside\n").unwrap();
        let mut files = Vec::new();
        assert!(browser_prefs(&root, true, &mut files).is_err());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn kitty_pid_requires_strict_decimal_nonzero_values() {
        for value in ["1", "42", "2147483647"] {
            assert!(kitty_pid(std::ffi::OsStr::new(value)).is_ok());
        }
        for value in [
            "",
            "0",
            "+1",
            " 1",
            "1 ",
            "1.0",
            "-1",
            "2147483648",
            "4294967295",
        ] {
            assert!(kitty_pid(std::ffi::OsStr::new(value)).is_err());
        }
    }

    #[test]
    fn wallpaper_backend_names_are_explicit() {
        use std::ffi::OsStr;

        assert_eq!(wallpaper_backend_name(None).unwrap(), "rewallpaper");
        for name in ["rewallpaper", "sway", "hyprpaper", "swww", "none"] {
            assert_eq!(
                wallpaper_backend_name(Some(OsStr::new(name))).unwrap(),
                name
            );
        }
        assert!(wallpaper_backend_name(Some(OsStr::new("unknown-backend"))).is_err());
    }

    #[test]
    fn browser_preserves_unmanaged_preferences() {
        let root = env::temp_dir().join(format!("retheme-browser-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let profile = root.join("profile");
        fs::create_dir_all(&profile).unwrap();
        fs::write(root.join("profiles.ini"), "Path=profile\n").unwrap();
        fs::write(profile.join("user.js"), "user_pref(\"unmanaged\", true);\n").unwrap();
        let mut files = Vec::new();
        browser_prefs(&root, true, &mut files).unwrap();
        assert_eq!(files.len(), 1);
        assert!(files[0].1.contains("unmanaged"));
        assert!(files[0].1.contains("ui.systemUsesDarkTheme"));
        let _ = fs::remove_dir_all(root);
    }
}

pub(crate) fn apply_renderers(dark: bool) {
    optional_command(
        "gsettings",
        [
            "set",
            "org.gnome.desktop.interface",
            "color-scheme",
            if dark { "prefer-dark" } else { "default" },
        ],
    );
    optional_command(
        "gsettings",
        ["set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita"],
    );
    reload_kitty();
    optional_command("pkill", ["-SIGUSR2", "btop"]);
}

fn kitty_pid(value: &std::ffi::OsStr) -> Result<i32, &'static str> {
    let value = value.to_str().ok_or("must be valid UTF-8")?;
    if value.is_empty() || !value.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err("must be strictly decimal");
    }
    let pid = value.parse::<i32>().map_err(|_| "is out of range")?;
    (pid != 0).then_some(pid).ok_or("must be nonzero")
}

fn reload_kitty() {
    match env::var_os("KITTY_PID") {
        Some(value) => match kitty_pid(&value) {
            Ok(pid) => match Command::new("kill")
                .args(["-SIGUSR1", &pid.to_string()])
                .status()
            {
                Ok(status) if status.success() => {}
                Ok(status) => eprintln!("warning: kill failed for Kitty PID {pid} ({status})"),
                Err(err) => eprintln!("warning: kill unavailable for Kitty PID {pid}: {err}"),
            },
            Err(error) => eprintln!("warning: invalid KITTY_PID ({error}); skipping Kitty reload"),
        },
        None => optional_command("pkill", ["-SIGUSR1", "-x", "kitty"]),
    }
}

fn optional_command<const N: usize>(program: &str, args: [&str; N]) {
    match Command::new(program).args(args).status() {
        Ok(status) if status.success() => {}
        Ok(status) => eprintln!("warning: {program} failed ({status})"),
        Err(err) => eprintln!("warning: {program} unavailable: {err}"),
    }
}

pub(crate) fn validate_wallpaper_backend() -> std::io::Result<()> {
    wallpaper_backend().map(|_| ())
}

fn wallpaper_backend() -> std::io::Result<&'static str> {
    wallpaper_backend_name(env::var_os("RETHEME_WALLPAPER_BACKEND").as_deref())
}

fn wallpaper_backend_name(value: Option<&std::ffi::OsStr>) -> std::io::Result<&'static str> {
    let Some(value) = value else {
        return Ok("rewallpaper");
    };
    match value.to_str() {
        Some("rewallpaper") => Ok("rewallpaper"),
        Some("sway") => Ok("sway"),
        Some("hyprpaper") => Ok("hyprpaper"),
        Some("swww") => Ok("swww"),
        Some("none") => Ok("none"),
        Some(_) => Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "RETHEME_WALLPAPER_BACKEND must be rewallpaper, sway, hyprpaper, swww, or none",
        )),
        None => Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "RETHEME_WALLPAPER_BACKEND must be valid UTF-8",
        )),
    }
}

pub(crate) fn apply_wallpaper(path: &Path) -> std::io::Result<()> {
    let backend = wallpaper_backend()?;
    if backend == "rewallpaper" && !rewallpaper_available() {
        return Ok(());
    }
    let (program, args): (&str, Vec<String>) = match backend {
        "rewallpaper" => (
            "rewallpaper",
            vec!["apply".into(), path.display().to_string()],
        ),
        "sway" => (
            "swaymsg",
            vec![
                "output".into(),
                "*".into(),
                "bg".into(),
                path.display().to_string(),
                "fill".into(),
            ],
        ),
        "hyprpaper" => (
            "hyprctl",
            vec![
                "hyprpaper".into(),
                "wallpaper".into(),
                format!(",{},cover", path.display()),
            ],
        ),
        "swww" => ("swww", vec!["img".into(), path.display().to_string()]),
        "none" => return Ok(()),
        _ => unreachable!(),
    };
    match Command::new(program).args(&args).status() {
        Ok(status) if status.success() => {}
        Ok(status) => eprintln!("warning: {program} failed ({status})"),
        Err(err) => eprintln!("warning: {program} unavailable: {err}"),
    }
    Ok(())
}

fn rewallpaper_available() -> bool {
    match Command::new("rewallpaper").arg("available").status() {
        Ok(status) if status.success() => true,
        Ok(status) => {
            eprintln!("warning: rewallpaper availability check failed ({status}); skipping wallpaper apply");
            false
        }
        Err(err) => {
            eprintln!("warning: rewallpaper unavailable: {err}; skipping wallpaper apply");
            false
        }
    }
}
