use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use crate::core::write_atomic;

fn home() -> Option<PathBuf> {
    env::var_os("HOME").map(PathBuf::from)
}

fn config_dir_from(xdg: Option<&Path>, home: Option<&Path>) -> Option<PathBuf> {
    xdg.map(Path::to_path_buf)
        .or_else(|| home.map(|home| home.join(".config")))
}

fn config_dir() -> Option<PathBuf> {
    config_dir_from(
        env::var_os("XDG_CONFIG_HOME")
            .as_deref()
            .map(|value| Path::new(value)),
        home().as_deref(),
    )
}

pub(crate) fn render_fixed(root: &Path, c: &[String; 16], dark: bool) -> std::io::Result<()> {
    let Some(config) = config_dir() else {
        eprintln!("warning: HOME and XDG_CONFIG_HOME are unset; skipping optional renderers");
        return Ok(());
    };
    let home = home();
    let mut files = Vec::new();
    let gtk = gtk_colors(c);
    optional(&config, "gtk-3.0", "gtk-3.0/gtk.css", &gtk, &mut files);
    optional(&config, "gtk-4.0", "gtk-4.0/gtk.css", &gtk, &mut files);
    let qt_colors = qt_colors(c);
    for qtver in ["qt5ct", "qt6ct"] {
        optional_qt(&config, qtver, &qt_colors, &mut files);
    }
    optional(&config, "kitty", "kitty/retheme-base16.conf", &format!("# generated by retheme\nforeground {}\nbackground {}\nselection_foreground {}\nselection_background {}\n", c[5], c[0], c[0], c[2]), &mut files);
    optional(&config, "btop", "btop/themes/retheme-base16.theme", &format!("# generated by retheme\nmain_bg = \"{}\"\nmain_fg = \"{}\"\nhi_fg = \"{}\"\nselected_bg = \"{}\"\nselected_fg = \"{}\"\n", c[0], c[5], c[13], c[2], c[5]), &mut files);
    optional(
        &config,
        "nvim",
        "nvim/colors/retheme-base16.lua",
        &nvim_colors(c, dark),
        &mut files,
    );
    browser_prefs(&config.join("mozilla/firefox"), dark, &mut files);
    browser_prefs(&config.join("librewolf"), dark, &mut files);
    if let Some(home) = &home {
        browser_prefs(&home.join(".librewolf"), dark, &mut files);
    }

    let stage = root
        .join("cache")
        .join(format!("retheme-render-{}", std::process::id()));
    let _ = fs::remove_dir_all(&stage);
    fs::create_dir_all(&stage)?;
    for (index, (_, content)) in files.iter().enumerate() {
        if let Err(err) = fs::write(stage.join(index.to_string()), content) {
            eprintln!("warning: renderer staging failed: {err}");
        }
    }
    for (index, (destination, _)) in files.iter().enumerate() {
        let Ok(content) = fs::read_to_string(stage.join(index.to_string())) else {
            continue;
        };
        if let Err(err) = write_atomic(destination, &content) {
            eprintln!(
                "warning: renderer write failed for {}: {err}",
                destination.display()
            );
        }
    }
    let _ = fs::remove_dir_all(stage);
    Ok(())
}

fn optional_qt(config: &Path, qtver: &str, colors: &str, files: &mut Vec<(PathBuf, String)>) {
    let dir = config.join(qtver);
    if optional(
        config,
        qtver,
        &format!("{qtver}/colors/reTheme.colors"),
        colors,
        files,
    ) {
        let colors_path = dir.join("colors/reTheme.colors");
        optional(
            config,
            qtver,
            &format!("{qtver}/{qtver}.conf"),
            &format!("[Appearance]\ncolor_scheme_path={}\ncustom_palette=true\nicon_theme=Adwaita\nstyle=Adwaita\n", colors_path.display()),
            files,
        );
    }
}

fn optional(
    base: &Path,
    label: &str,
    relative: &str,
    content: &str,
    files: &mut Vec<(PathBuf, String)>,
) -> bool {
    let destination = base.join(relative);
    if destination.parent().is_some_and(Path::is_dir) {
        files.push((destination, content.into()));
        true
    } else {
        eprintln!("warning: {label} config directory unavailable; skipping renderer");
        false
    }
}

fn gtk_colors(c: &[String; 16]) -> String {
    format!("@define-color base00 {};\n@define-color base05 {};\n@define-color base0D {};\nwindow, dialog {{ background-color: @base00; color: @base05; }}\n", c[0], c[5], c[13])
}

fn nvim_colors(c: &[String; 16], dark: bool) -> String {
    format!("local c = {{ bg = '{}', fg = '{}', red = '{}', green = '{}', yellow = '{}', blue = '{}', magenta = '{}', cyan = '{}' }}\nnvim.cmd('hi clear')\nnvim.o.background = '{}'\nfor _, group in ipairs({{'Normal', 'NormalFloat'}}) do vim.api.nvim_set_hl(0, group, {{ fg = c.fg, bg = c.bg }}) end\nvim.api.nvim_set_hl(0, 'Comment', {{ fg = '{}' }})\nvim.api.nvim_set_hl(0, 'String', {{ fg = c.green }})\nvim.api.nvim_set_hl(0, 'Function', {{ fg = c.blue }})\nvim.api.nvim_set_hl(0, 'Keyword', {{ fg = c.magenta }})\n", c[0], c[5], c[8], c[11], c[10], c[13], c[14], c[12], if dark { "dark" } else { "light" }, c[3])
}
fn qt_colors(c: &[String; 16]) -> String {
    let indexes = [
        5, 0, 0, 3, 4, 5, 13, 7, 3, 8, 9, 10, 11, 12, 13, 14, 15, 4, 3, 13, 3,
    ];
    let active = indexes
        .iter()
        .map(|index| format!("#ff{}", &c[*index][1..]))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[ColorScheme]\nactive_colors={active}\ndisabled_colors={active}\ninactive_colors={active}\n")
}

fn browser_prefs(root: &Path, dark: bool, files: &mut Vec<(PathBuf, String)>) {
    let Ok(text) = fs::read_to_string(root.join("profiles.ini")) else {
        return;
    };
    let Ok(canonical_root) = root.canonicalize() else {
        return;
    };
    for line in text.lines().filter_map(|l| l.strip_prefix("Path=")) {
        let relative = Path::new(line);
        if relative.is_absolute()
            || relative
                .components()
                .any(|c| matches!(c, std::path::Component::ParentDir))
        {
            continue;
        }
        let profile = root.join(relative);
        let Ok(profile) = profile.canonicalize() else {
            continue;
        };
        if !profile.starts_with(&canonical_root) || !profile.is_dir() {
            eprintln!("warning: browser profile outside config root; skipping");
            continue;
        }
        let prefs = [
            ("ui.systemUsesDarkTheme", if dark { "1" } else { "0" }),
            ("browser.theme.toolbar-theme", if dark { "0" } else { "2" }),
            ("browser.theme.content-theme", if dark { "0" } else { "2" }),
        ];
        let path = profile.join("user.js");
        let old = match fs::read_to_string(&path) {
            Ok(old) => old,
            Err(_) if !path.exists() => String::new(),
            Err(err) => {
                eprintln!(
                    "warning: cannot read {}; skipping browser profile: {err}",
                    path.display()
                );
                continue;
            }
        };
        let mut out: Vec<String> = old
            .lines()
            .filter(|line| {
                !prefs
                    .iter()
                    .any(|(key, _)| line.starts_with(&format!("user_pref(\"{key}\",")))
            })
            .map(str::to_string)
            .collect();
        for (key, value) in prefs {
            out.push(format!("user_pref(\"{key}\", {value});"));
        }
        files.push((path, out.join("\n") + "\n"));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn xdg_config_works_without_home() {
        assert_eq!(
            config_dir_from(Some(Path::new("/tmp/config")), None),
            Some(PathBuf::from("/tmp/config"))
        );
        assert_eq!(config_dir_from(None, None), None);
    }

    #[test]
    fn optional_targets_and_generated_helpers_are_selected() {
        let root = env::temp_dir().join(format!("retheme-renderers-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        for path in ["gtk-3.0", "qt5ct/colors", "nvim/colors"] {
            fs::create_dir_all(root.join(path)).unwrap();
        }
        let colors: [String; 16] = std::array::from_fn(|index| format!("#{index:06X}"));
        let mut files = Vec::new();
        let gtk = gtk_colors(&colors);
        optional(&root, "gtk", "gtk-3.0/gtk.css", &gtk, &mut files);
        let qt = qt_colors(&colors);
        optional_qt(&root, "qt5ct", &qt, &mut files);
        let nvim = nvim_colors(&colors, true);
        optional(
            &root,
            "nvim",
            "nvim/colors/retheme-base16.lua",
            &nvim,
            &mut files,
        );

        assert_eq!(
            files.iter().map(|(path, _)| path).collect::<Vec<_>>(),
            vec![
                &root.join("gtk-3.0/gtk.css"),
                &root.join("qt5ct/colors/reTheme.colors"),
                &root.join("qt5ct/qt5ct.conf"),
                &root.join("nvim/colors/retheme-base16.lua"),
            ]
        );
        assert!(files[0].1.contains("@define-color base00 #000000;"));
        assert!(files[1].1.starts_with("[ColorScheme]\nactive_colors=#ff"));
        assert!(files[3].1.contains("nvim.o.background = 'dark'"));

        fs::create_dir_all(root.join("qt6ct")).unwrap();
        let mut files = Vec::new();
        optional_qt(&root, "qt6ct", &qt, &mut files);
        assert!(files.is_empty());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn browser_preserves_unmanaged_preferences() {
        let root = env::temp_dir().join(format!("retheme-browser-{}", std::process::id()));
        let _ = fs::remove_dir_all(&root);
        let profile = root.join("profile");
        fs::create_dir_all(&profile).unwrap();
        fs::write(root.join("profiles.ini"), "Path=profile\n").unwrap();
        fs::write(profile.join("user.js"), "user_pref(\"unmanaged\", true);\n").unwrap();
        let mut files = Vec::new();
        browser_prefs(&root, true, &mut files);
        assert_eq!(files.len(), 1);
        assert!(files[0].1.contains("unmanaged"));
        assert!(files[0].1.contains("ui.systemUsesDarkTheme"));
        let _ = fs::remove_dir_all(root);
    }
}

pub(crate) fn apply_renderers(dark: bool) {
    optional_command(
        "gsettings",
        [
            "set",
            "org.gnome.desktop.interface",
            "color-scheme",
            if dark { "prefer-dark" } else { "default" },
        ],
    );
    optional_command(
        "gsettings",
        ["set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita"],
    );
    optional_command("pkill", ["-SIGUSR1", "kitty"]);
    optional_command("pkill", ["-SIGUSR2", "btop"]);
}

fn optional_command<const N: usize>(program: &str, args: [&str; N]) {
    match Command::new(program).args(args).status() {
        Ok(status) if status.success() => {}
        Ok(status) => eprintln!("warning: {program} failed ({status})"),
        Err(err) => eprintln!("warning: {program} unavailable: {err}"),
    }
}

pub(crate) fn apply_wallpaper(path: &Path) {
    match Command::new("rewallpaper").arg("apply").arg(path).status() {
        Ok(status) if status.success() => {}
        Ok(status) => eprintln!("warning: rewallpaper apply failed ({status})"),
        Err(err) => eprintln!("warning: rewallpaper unavailable: {err}"),
    }
}
